site_name: WP Assure
site_url:  http://wpassure.readthedocs.org/
site_description: Test code using acceptance tests and sharable, defined file and database snapshots.
repo_url: https://github.com/10up/wpassure

nav:
  - Home: index.md
  - Cookbook: cookbook.md

theme: mkdocs
